In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Bihar_Election_Results .csv')

In [21]:
df

,Election Year,Position,Name,Votes,Votes %,Party,AC name,AC No
0,2010,1,Rajesh Singh,42289,29.40%,Janata Dal (United),Valmiki Nagar,1
1,2010,2,Mukesh Kumar Kushwaha,27618,19.20%,Rashtriya Janata Dal,Valmiki Nagar,1
2,2010,3,Dheerendra Pratap Singh,20886,14.50%,Bahujan Samaj Party,Valmiki Nagar,1
3,2010,4,Irshad Hussain,17747,12.40%,Indian National Congress,Valmiki Nagar,1
4,2010,5,Deep Narayan Mahato,14047,9.80%,Independent,Valmiki Nagar,1
...,...,...,...,...,...,...,...,...
12296,2005-Feb,15,Chandeshwar Prasad Gupt,534,0.60%,Independent,Chakai,243
12297,2005-Feb,16,Tirpit Singh,498,0.60%,Independent,Chakai,243
12298,2005-Feb,17,Surendra Rajbansi,437,0.50%,Independent,Chakai,243
12299,2005-Feb,18,Nawin Kumar Paswan,415,0.50%,Independent,Chakai,243
12300,2005-Feb,19,Ajay Kumar,407,0.50%,Independent,Chakai,243

In [22]:
df.columns

Index(['Election Year', 'Position', 'Name', 'Votes', 'Votes %', 'Party',
       'AC name', 'AC No'],
      dtype='object')

In [18]:
df.dtypes

ElectionYear    object
Position         int64
Name            object
Votes            int64
Votes %         object
Party           object
AC name         object
AC No            int64
dtype: object

 # Start Renaming Couumns to access it

In [5]:
df.rename(columns={'Election Year':'ElectionYear'},inplace=True)
df.rename(columns={'Votes %':'VotesPercentage'},inplace=True)
df.rename(columns={'AC name':'ACname'},inplace=True)
df.rename(columns={'AC No':'ACNo'},inplace=True)

# Change datatype of Electionyear from object to datatime

In [7]:
df['ElectionYear']=pd.to_datetime(df['ElectionYear'])

In [8]:
# Extract Year part from Election year
df['Year']= df.ElectionYear.dt.year

In [36]:
df.head()

,ElectionYear,Position,Name,Votes,VotesPercentage,Party,ACname,ACNo,Year
0,2010-01-01,1,Rajesh Singh,42289,29.40%,Janata Dal (United),Valmiki Nagar,1,2010
1,2010-01-01,2,Mukesh Kumar Kushwaha,27618,19.20%,Rashtriya Janata Dal,Valmiki Nagar,1,2010
2,2010-01-01,3,Dheerendra Pratap Singh,20886,14.50%,Bahujan Samaj Party,Valmiki Nagar,1,2010
3,2010-01-01,4,Irshad Hussain,17747,12.40%,Indian National Congress,Valmiki Nagar,1,2010
4,2010-01-01,5,Deep Narayan Mahato,14047,9.80%,Independent,Valmiki Nagar,1,2010

In [32]:
print('Total number of differnt party=', df.Party.nunique())

Total number of differnt party= 222

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12301 entries, 0 to 12300
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ElectionYear     12301 non-null  datetime64[ns]
 1   Position         12301 non-null  int64
 2   Name             12301 non-null  object
 3   Votes            12301 non-null  int64
 4   VotesPercentage  12301 non-null  object
 5   Party            12301 non-null  object
 6   ACname           12301 non-null  object
 7   ACNo             12301 non-null  int64
 8   Year             12301 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 865.0+ KB

In [95]:
print('Differnt Election year=',df.ElectionYear.unique())

Differnt Election year= ['2010-01-01T00:00:00.000000000' '2015-01-01T00:00:00.000000000'
 '2005-10-01T00:00:00.000000000' '2005-02-01T00:00:00.000000000']

df.groupby('ElectionYear').max('Votes')

In [10]:
newdf = df[(df.Votes == 103462) | (df.Votes==117915) | (df.Votes==91419)| (df.Votes==102850)]

In [70]:
newdf

,ElectionYear,Position,Name,Votes,VotesPercentage,Party,ACname,ACNo,Year
2614,2010-01-01,1,Nand Kishore Yadav,91419,68.10%,Bharatiya Janta Party,Patna Sahib,184,2010
4566,2015-01-01,1,Arun Kumar,102850,53.00%,Rashtriya Janata Dal,Saharsa,75,2015
8543,2005-10-01,1,Navin Kishore Pd. Sinha,117915,69.30%,Bharatiya Janta Party,Phulwari,188,2005
11506,2005-02-01,1,Navin Kishore Pd. Sinha,103462,59.10%,Bharatiya Janta Party,Phulwari (SC),188,2005

# a. Determine the winning party for every election at the state level. A party has the highest total votes is considered the winner here.

In [16]:
print('Winning party in every election  ' ,np.array(newdf.iloc[:,5]))

Winning party in every election   ['Bharatiya Janta Party' 'Rashtriya Janata Dal' 'Bharatiya Janta Party'
 'Bharatiya Janta Party']

In [38]:
Electiondata = df.sort_values('ElectionYear')

In [81]:
Electiondata.head(5)

,ElectionYear,Position,Name,Votes,VotesPercentage,Party,ACname,ACNo,Year
12300,2005-02-01,19,Ajay Kumar,407,0.50%,Independent,Chakai,243,2005
10177,2005-02-01,2,Hari Prasad Sah,18923,21.50%,Janata Dal (United),Darbhanga Rural,82,2005
10176,2005-02-01,1,Anis Ahmad,20165,22.90%,Rashtriya Janata Dal,Darbhanga Rural,82,2005
10175,2005-02-01,10,Jai Narayan Prasad,713,0.90%,Independent,Alinagar,81,2005
10174,2005-02-01,9,Darpi Malik,730,0.90%,Independent,Alinagar,81,2005

# b. determine the list of swing seats for the state. A swing seat is a constituency which has a different winner in every election. The elections are held in the order 2005-Feb, 2005-Oct, 2010 and 2015.

In [82]:
#ACnameUniquedata = ElectiondatasortintermsofVote.ACname.unique()
#res = ElectiondatasortintermsofVote.groupby('ElectionYear').max('Votes')
#pd.DataFrame(res)

# c.Determine the top 8 parties at the state-level in each election in terms of getting the most votes.

In [71]:
ElectiondatasortintermsofVote = Electiondata.sort_values('Votes',ascending=False)

In [22]:
Top8parties = ElectiondatasortintermsofVote.head(8)

In [23]:
print('top 8 parties' ,np.array(Top8parties.iloc[:,5]))

top 8 parties ['Bharatiya Janta Party' 'Bharatiya Janta Party' 'Rashtriya Janata Dal'
 'Indian National Congress' 'Bharatiya Janta Party' 'Janata Dal (United)'
 'Indian National Congress' 'Rashtriya Janata Dal']

In [94]:
Top8parties

,ElectionYear,Position,Name,Votes,VotesPercentage,Party,ACname,ACNo,Year
8543,2005-10-01,1,Navin Kishore Pd. Sinha,117915,69.30%,Bharatiya Janta Party,Phulwari,188,2005
11506,2005-02-01,1,Navin Kishore Pd. Sinha,103462,59.10%,Bharatiya Janta Party,Phulwari (SC),188,2005
4566,2015-01-01,1,Arun Kumar,102850,53.00%,Rashtriya Janata Dal,Saharsa,75,2015
4244,2015-01-01,1,Abdul Jalil Mastan,100135,59.20%,Indian National Congress,Amour,56,2015
4850,2015-01-01,1,Suresh Kumar Sharma,95594,55.10%,Bharatiya Janta Party,Muzaffarpur,94,2015
6184,2015-01-01,1,Shyam Rajak,94094,49.80%,Janata Dal (United),Phulwari,188,2015
6235,2015-01-01,1,Siddharth,94088,54.40%,Indian National Congress,Bihpur,152,2015
6345,2015-01-01,1,Shambhu Nath Yadav,94079,52.00%,Rashtriya Janata Dal,Bodh Gaya,229,2015

# d. Determine the minimum votes that each party in the top 8 of the 2015 election secured among all the past elections. Do this for all constituencies.

In [47]:
# Finding top 8 parties of 2015
Electiondataof2015 = ElectiondatasortintermsofVote[ElectiondatasortintermsofVote['Year']==2015]
Top8partiesYearby2015 = ElectiondatasortintermsofVote.head(8)

In [61]:
condition1 =(ElectiondatasortintermsofVote['Party']=='Bharatiya Janta Party') | (ElectiondatasortintermsofVote['Party']=='Rashtriya Janata Dal')| (ElectiondatasortintermsofVote['Party']=='Indian National Congress') | (ElectiondatasortintermsofVote['Party']=='Janata Dal (United)') 
condition2 = (ElectiondatasortintermsofVote['Year']!=2015) & (ElectiondatasortintermsofVote['Year']!=2019)
condition = condition1 & condition2

In [64]:
ElectiondatasortintermsofVotewithcondition = ElectiondatasortintermsofVote
ElectiondatasortintermsofVotewithcondition.where(condition,inplace=True)

In [66]:
ElectiondatasortintermsofVotewithcondition.groupby('Party').min('Votes')

                          Position   Votes  ACNo    Year
Party
Bharatiya Janta Party          1.0  2432.0   2.0  2005.0
Indian National Congress       1.0  1100.0   1.0  2005.0
Janata Dal (United)            1.0   216.0   1.0  2005.0
Rashtriya Janata Dal           1.0  1386.0   1.0  2005.0

In [67]:
print('Minimum Votes secured by top 8  party in 2015  among all past election =',ElectiondatasortintermsofVotewithcondition.groupby('Party').min('Votes').Votes)

Minimum Votes secured by top 8  party in 2015  among all past election = Party
Bharatiya Janta Party       2432.0
Indian National Congress    1100.0
Janata Dal (United)          216.0
Rashtriya Janata Dal        1386.0
Name: Votes, dtype: float64

# f. Determine the stronghold party-seats. A stronghold seat is one that is won by the same party in all the elections.

In [131]:
ElectiondatasortintermsofVote.groupby(['ACname','Party']).max('Votes')

                                                            Position  Votes  \
ACname  Party
Agiaon  Bahujan Mukti Party                                        6   1065
        Bahujan Samaj Party                                       13   1297
        Bharatiya Janta Party                                      2  37572
        Communist Party Of India (MARXIST-LENINIST) (LI...         3  30120
        Communist Party Of India (Marxist-Leninist) (Li...         3  31789
...                                                              ...    ...
Ziradei Rashtriya Samanta Dal                                     15    374
        Samajwadi Janata Party (RASHTRIYA)                        20    833
        Samajwadi Party                                           23   3162
        Shiv Sena                                                 10   1731
        Swatantra Samaj Party                                     16    300

                                                            ACNo  Year
ACname  Party
Agiaon  Bahujan Mukti Party                                  195  2015
        Bahujan Samaj Party                                  195  2015
        Bharatiya Janta Party                                195  2015
        Communist Party Of India (MARXIST-LENINIST) (LI...   195  2010
        Communist Party Of India (Marxist-Leninist) (Li...   195  2015
...                                                          ...   ...
Ziradei Rashtriya Samanta Dal                                106  2015
        Samajwadi Janata Party (RASHTRIYA)                   106  2010
        Samajwadi Party                                      106  2015
        Shiv Sena                                            106  2015
        Swatantra Samaj Party                                106  2015

[5194 rows x 4 columns]

In [ ]:
def todermineclsoe(df):
    if

In [140]:
ElectiondatasortintermsofVote

,ElectionYear,Position,Name,Votes,VotesPercentage,Party,ACname,ACNo,Year
8543,2005-10-01,1,Navin Kishore Pd. Sinha,117915,69.30%,Bharatiya Janta Party,Phulwari,188,2005
11506,2005-02-01,1,Navin Kishore Pd. Sinha,103462,59.10%,Bharatiya Janta Party,Phulwari (SC),188,2005
4566,2015-01-01,1,Arun Kumar,102850,53.00%,Rashtriya Janata Dal,Saharsa,75,2015
4244,2015-01-01,1,Abdul Jalil Mastan,100135,59.20%,Indian National Congress,Amour,56,2015
4850,2015-01-01,1,Suresh Kumar Sharma,95594,55.10%,Bharatiya Janta Party,Muzaffarpur,94,2015
...,...,...,...,...,...,...,...,...,...
11563,2005-02-01,25,Lallu Singh,148,0.10%,Independent,Masaurhi (SC),189,2005
6128,2015-01-01,34,Hare Krishna Prasad,143,0.10%,Independent,Kumhrarh,183,2015
12240,2005-02-01,21,Ram Balak Prasad,140,0.10%,Independent,Warsaliganj,239,2005
11565,2005-02-01,26,Manoj Kumar (EAST LOHANIPUR),98,0.10%,Independent,Masaurhi (SC),189,2005
11564,2005-02-01,26,Ram Babu Kumar Sankrity,98,0.10%,Independent,Masaurhi (SC),189,2005

In [138]:
Top2const

      Position   Votes  ACNo
Year
2005        33  117915   243
2010        31   91419   243
2015        34  102850   243